name: Docker Image CI

on: 
  push:
    branches:
      - master

jobs:

  build:

    runs-on: [self-hosted]

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag jojii/matrix_email_bridge
    - name: Login to GitHub Package Registry
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
    - name: push into registry
      run:  docker push jojii/matrix_email_bridge:latest
